import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";
import { Bio } from "../components/Bio";
import { getSortedPostsData } from "../lib/posts";
import { GetStaticProps } from "next";
import Layout from "../components/Layout";
import julian from "../public/images/profile1.jpg";

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
};

type HomeProps = {
  allPostsData: any;
};

export default function Home({ allPostsData }: HomeProps) {
  return (
    <Layout>
      <Head>
        <title>jayastronomic</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className={styles.container}>
        <div className={styles.header}>
          <div className={styles.imageWrapper}>
            <Image className={styles.image} src={julian} alt="Julian" />
          </div>
          <h1>Julian Smith</h1>
        </div>
        <Bio />
        <h2>Blog</h2>
        <ul>
          {allPostsData.map(({ id, date, title }: any) => (
            <li key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </section>
    </Layout>
  );
}
